before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: OaXgN9F8RxIf+Fyo4Gmi58AoswHMFaVt/aLp4krUVPlevu5bDQE0gm77YrtuvVI3ZUETC2H3jxex3fCAcq86Qonj0cdbUGKJLjAK4u8x3KeaWGfaSVq9BOzSfKQWbLcv+9LIa6HKUybJTleqgTaMoqlt61oO+RqhldoEVRyEGSYRpjZRsE8yyP2HOYp/HRdk5cVhGXNqZL2VwxD6tVFiyFYDE38VopI+tGUfCJkkMBtxSSuySvCathvm8OQAjiYM8eCXO089zZ0Wgz7/oZdBsDEmmtb+nOfWnHGBDHo/yJ6mVGFfjjxvYK0S7KWNUxRgLjXm9txKFmaxLnjaAVOGbc+NUa1obRQvKL7iKCfly5ulyB9VQZUl5xeXJkPUuOf3hnL8kXiBxPkpRCei4OyIwwMfr514j0bLPH9Q7Lf24YEkZjSwBzrmU6p1bFZUTwbDmqZ67kV5CXtJXTe2NuYgiuu4zVc82Q12tftJasZexRMFs76AfgNGhmusW9dx6JXGTQ0jXkSxVa2z67YoJdx5ZDjJO6jwEhkBTEI6CrWYe9q+vgHEcIVhjkNaVDO9vuWFMr8aRDx482ZQAFC3oWE6AFDNcR1XWD9zztiF5RU21JbZFa1AvD5ZSdM/jNkTMsFTHsNsLi90bzgEWWVd8rma1dpiqpohBICw9XjYqgx29hw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
